import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./(Providers)/NextUiProvider";
import localFont from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

const rbBold = localFont({
  src:[
    {
      path:'../public/fonts/RB Bold.ttf',
      weight:'800'
    },

  ],
  variable:'--font-rb-bold'
})
const rbLight = localFont({
  src:[
    {
      path:'../public/fonts/RB Light.ttf',
      // weight:'800'
    },

  ],
  variable:'--font-rb-light'
})
const rbRegular = localFont({
  src:[
    {
      path:'../public/fonts/RB Regular.ttf',
      // weight:'800'
    },

  ],
  variable:'--font-rb-reg'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${rbBold.variable} ${rbRegular.variable} ${rbLight.variable} font-sans`}>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
