import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./(Providers)/NextUiProvider";
import localFont from 'next/font/local';

const inter = Inter({ subsets: ["latin"] });

const bhaji = localFont({
  src:[
    {
      path:'../public/fonts/Bahij TheSansArabic Bold.ttf',
      weight:'800'
    }
  ],
  variable:'--font-bhaji'
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${bhaji.variable} font-sans`}>
      <body className={inter.className}>
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
